"""
Database Models for llmscm.com
"""

from .database import (
    Base,
    # Enums
    UserRole,
    SubscriptionTier,
    IndustryCategory,
    PromptType,
    LLMProvider,
    LLMRunStatus,
    SentimentPolarity,
    SourceCategory,
    JobPriority,
    # Models
    User,
    UserAPIKey,
    Project,
    Brand,
    Competitor,
    Keyword,
    PromptTemplate,
    Prompt,
    LLMRun,
    LLMResponse,
    BrandMention,
    CitationSource,
    Citation,
    VisibilityScore,
    AggregatedScore,
    AuditLog,
    ScheduledJob,
)

from .visibility import (
    # Enums
    MentionType,
    CitationPurpose,
    OutreachStatus,
    ContentGapType,
    # Models
    FanOutQuery,
    ShoppingRecommendation,
    CitationDetail,
    ShareOfVoice,
    PositionTracking,
    PromptVolumeEstimate,
    OutreachOpportunity,
    ContentGap,
    KeywordAnalysisResult,
    ExtractedEntity,
    AIOResult,
)

__all__ = [
    "Base",
    # Enums
    "UserRole",
    "SubscriptionTier",
    "IndustryCategory",
    "PromptType",
    "LLMProvider",
    "LLMRunStatus",
    "SentimentPolarity",
    "SourceCategory",
    "JobPriority",
    "MentionType",
    "CitationPurpose",
    "OutreachStatus",
    "ContentGapType",
    # Core Models
    "User",
    "UserAPIKey",
    "Project",
    "Brand",
    "Competitor",
    "Keyword",
    "PromptTemplate",
    "Prompt",
    "LLMRun",
    "LLMResponse",
    "BrandMention",
    "CitationSource",
    "Citation",
    "VisibilityScore",
    "AggregatedScore",
    "AuditLog",
    "ScheduledJob",
    # Visibility Models
    "FanOutQuery",
    "ShoppingRecommendation",
    "CitationDetail",
    "ShareOfVoice",
    "PositionTracking",
    "PromptVolumeEstimate",
    "OutreachOpportunity",
    "ContentGap",
    "KeywordAnalysisResult",
    "ExtractedEntity",
    "AIOResult",
]
