"""
llmscm.com - Visibility Analytics Models
Extended models for detailed visibility tracking, fan-out queries, citations, and AI prompt volume
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum as PyEnum
from typing import Optional, List
from uuid import uuid4

from sqlalchemy import (
    Column, String, Text, Integer, Float, Boolean, DateTime,
    ForeignKey, Enum, JSON, Numeric, Index, UniqueConstraint,
    CheckConstraint, func
)
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.orm import relationship

from .database import Base, LLMProvider, SourceCategory, SentimentPolarity


# ============================================================================
# ENUMS FOR VISIBILITY TRACKING
# ============================================================================

class MentionType(str, PyEnum):
    """Types of brand mentions"""
    DIRECT = "direct"           # Brand name mentioned directly
    RECOMMENDATION = "recommendation"  # Recommended as solution
    COMPARISON = "comparison"    # Compared with competitors
    EXAMPLE = "example"          # Used as an example
    ALTERNATIVE = "alternative"  # Listed as alternative
    TOP_PICK = "top_pick"        # Featured as top/best choice


class CitationPurpose(str, PyEnum):
    """Why a source was cited"""
    AUTHORITY = "authority"      # Expert/authoritative source
    DOCUMENTATION = "documentation"  # Official docs
    REVIEW = "review"            # Review or comparison
    NEWS = "news"                # News/current events
    TUTORIAL = "tutorial"        # How-to/guide
    RESEARCH = "research"        # Academic/research
    ECOMMERCE = "ecommerce"      # Shopping/product page


class OutreachStatus(str, PyEnum):
    """Status of outreach opportunity"""
    NEW = "new"
    IN_PROGRESS = "in_progress"
    CONTACTED = "contacted"
    COMPLETED = "completed"
    DISMISSED = "dismissed"


class ContentGapType(str, PyEnum):
    """Types of content gaps identified"""
    MISSING_PAGE = "missing_page"      # Need to create new content
    THIN_CONTENT = "thin_content"      # Existing content needs expansion
    NO_BACKLINK = "no_backlink"        # Source exists but no link to us
    COMPETITOR_ONLY = "competitor_only"  # Competitor cited, we're not
    FORMAT_GAP = "format_gap"          # Need different content format


# ============================================================================
# FAN-OUT QUERIES (Web Search Queries Generated by AI)
# ============================================================================

class FanOutQuery(Base):
    """Web search queries generated by AI models to ground their responses"""
    __tablename__ = "fan_out_queries"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    llm_run_id = Column(UUID(as_uuid=True), ForeignKey("llm_runs.id", ondelete="CASCADE"), nullable=False)
    response_id = Column(UUID(as_uuid=True), ForeignKey("llm_responses.id", ondelete="CASCADE"))

    # The search query generated by AI
    query_text = Column(Text, nullable=False)
    query_hash = Column(String(64), nullable=False, index=True)

    # Query characteristics
    query_type = Column(String(50))  # "informational", "navigational", "transactional"
    query_intent = Column(String(100))  # Intent classification

    # Position in search sequence
    query_position = Column(Integer, default=1)  # Order in which AI searched

    # Keywords extracted from query
    extracted_keywords = Column(ARRAY(String), default=[])

    # Brands mentioned in query
    brands_in_query = Column(ARRAY(String), default=[])

    # Whether our brand appeared in results
    brand_appeared_in_results = Column(Boolean, default=False)
    brand_result_position = Column(Integer)  # Position if appeared

    # Results metadata (if captured)
    result_count = Column(Integer)
    top_domains = Column(ARRAY(String), default=[])  # Top 10 domains in results

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_fanout_run', 'llm_run_id'),
        Index('idx_fanout_query_hash', 'query_hash'),
    )


# ============================================================================
# SHOPPING RECOMMENDATIONS
# ============================================================================

class ShoppingRecommendation(Base):
    """Product recommendations and purchase suggestions in AI responses"""
    __tablename__ = "shopping_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    response_id = Column(UUID(as_uuid=True), ForeignKey("llm_responses.id", ondelete="CASCADE"), nullable=False)

    # Product details
    product_name = Column(String(500), nullable=False)
    brand_name = Column(String(255))
    product_category = Column(String(255))

    # Is this our brand?
    is_own_brand = Column(Boolean, default=False)
    brand_id = Column(UUID(as_uuid=True), ForeignKey("brands.id", ondelete="SET NULL"))
    competitor_id = Column(UUID(as_uuid=True), ForeignKey("competitors.id", ondelete="SET NULL"))

    # Position and context
    recommendation_position = Column(Integer, nullable=False)  # 1st, 2nd, 3rd recommendation
    recommendation_type = Column(String(50))  # "best_overall", "budget", "premium", "runner_up"
    context_snippet = Column(Text)

    # Pricing mentioned
    price_mentioned = Column(String(100))
    price_value = Column(Numeric(10, 2))

    # Links/sources
    product_url = Column(Text)
    source_url = Column(Text)  # Where AI got info

    # Sentiment of recommendation
    sentiment = Column(Enum(SentimentPolarity), default=SentimentPolarity.POSITIVE)
    recommendation_strength = Column(Float)  # 0-1, how strongly recommended

    # Features/pros mentioned
    pros_mentioned = Column(ARRAY(String), default=[])
    cons_mentioned = Column(ARRAY(String), default=[])

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_shopping_response', 'response_id'),
        Index('idx_shopping_brand', 'brand_id'),
        Index('idx_shopping_position', 'recommendation_position'),
    )


# ============================================================================
# ENHANCED CITATION TRACKING
# ============================================================================

class CitationDetail(Base):
    """Detailed citation analysis - why each source was cited"""
    __tablename__ = "citation_details"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    citation_id = Column(UUID(as_uuid=True), ForeignKey("citations.id", ondelete="CASCADE"), nullable=False)

    # Why this source was cited
    citation_purpose = Column(Enum(CitationPurpose), nullable=False)
    purpose_confidence = Column(Float, default=0.8)

    # Context analysis
    context_before = Column(Text)  # Text before citation
    context_after = Column(Text)   # Text after citation
    full_sentence = Column(Text)   # Complete sentence containing citation

    # What claim does this citation support?
    supported_claim = Column(Text)
    claim_type = Column(String(100))  # "factual", "opinion", "recommendation", "comparison"

    # Brand association
    brands_in_context = Column(ARRAY(String), default=[])
    mentions_our_brand = Column(Boolean, default=False)
    mentions_competitor = Column(Boolean, default=False)

    # Source quality signals
    is_primary_source = Column(Boolean, default=False)  # Official/primary vs secondary
    is_current = Column(Boolean, default=True)  # Recent/current info
    estimated_publish_date = Column(DateTime)

    # Page metadata (if crawled)
    page_title = Column(Text)
    page_description = Column(Text)
    page_type = Column(String(50))  # "article", "product", "documentation", "forum"

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_citation_detail', 'citation_id'),
        Index('idx_citation_purpose', 'citation_purpose'),
    )


# ============================================================================
# SHARE OF VOICE TRACKING
# ============================================================================

class ShareOfVoice(Base):
    """Share of Voice metrics - how often brand mentioned vs competitors"""
    __tablename__ = "share_of_voice"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    keyword_id = Column(UUID(as_uuid=True), ForeignKey("keywords.id", ondelete="SET NULL"))

    # Time period
    period_start = Column(DateTime, nullable=False)
    period_end = Column(DateTime, nullable=False)
    period_type = Column(String(20), nullable=False)  # "daily", "weekly", "monthly"

    # LLM scope (null for aggregate)
    provider = Column(Enum(LLMProvider))

    # Our brand metrics
    brand_mention_count = Column(Integer, default=0)
    brand_mention_rate = Column(Float, default=0)  # % of responses mentioning us

    # Total mentions in responses
    total_entity_mentions = Column(Integer, default=0)
    total_responses_analyzed = Column(Integer, default=0)

    # Share of Voice calculation
    share_of_voice = Column(Float, default=0)  # 0-100%

    # Competitor breakdown
    competitor_shares = Column(JSONB, default={})  # {competitor_name: share %}

    # Position metrics
    avg_mention_position = Column(Float)  # Average position when mentioned
    first_position_count = Column(Integer, default=0)  # Times mentioned first

    # Trend
    sov_change = Column(Float)  # Change from previous period
    trend = Column(String(20))  # "up", "down", "stable"

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_sov_project_period', 'project_id', 'period_start'),
        Index('idx_sov_keyword', 'keyword_id', 'period_start'),
        UniqueConstraint('project_id', 'keyword_id', 'provider', 'period_start', 'period_type',
                        name='uq_sov_period'),
    )


class PositionTracking(Base):
    """Track average brand position in AI responses"""
    __tablename__ = "position_tracking"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    keyword_id = Column(UUID(as_uuid=True), ForeignKey("keywords.id", ondelete="SET NULL"))

    # Entity being tracked
    entity_name = Column(String(255), nullable=False)
    is_own_brand = Column(Boolean, default=False)

    # Time period
    tracking_date = Column(DateTime, nullable=False)

    # LLM scope
    provider = Column(Enum(LLMProvider))

    # Position metrics
    avg_position = Column(Float, nullable=False)  # Average position (1=first)
    min_position = Column(Integer)  # Best position achieved
    max_position = Column(Integer)  # Worst position
    position_std_dev = Column(Float)  # Consistency measure

    # Frequency at each position
    position_distribution = Column(JSONB, default={})  # {1: count, 2: count, ...}

    # Comparison
    position_vs_yesterday = Column(Float)  # Position change
    position_vs_last_week = Column(Float)

    # Sample size
    mentions_analyzed = Column(Integer, nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_position_project_date', 'project_id', 'tracking_date'),
        Index('idx_position_entity', 'entity_name', 'tracking_date'),
    )


# ============================================================================
# AI PROMPT VOLUME ESTIMATION
# ============================================================================

class PromptVolumeEstimate(Base):
    """Estimated monthly AI prompt volume for topics"""
    __tablename__ = "prompt_volume_estimates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    keyword_id = Column(UUID(as_uuid=True), ForeignKey("keywords.id", ondelete="SET NULL"))

    # Topic/keyword
    topic = Column(String(500), nullable=False)
    topic_cluster = Column(String(255))  # Group of related topics

    # Estimation period
    estimate_month = Column(DateTime, nullable=False)

    # Volume estimates per platform
    total_estimated_prompts = Column(Integer, nullable=False)
    chatgpt_volume = Column(Integer, default=0)
    claude_volume = Column(Integer, default=0)
    gemini_volume = Column(Integer, default=0)
    perplexity_volume = Column(Integer, default=0)

    # Confidence and methodology
    estimation_method = Column(String(100))  # "google_trends", "inference", "third_party"
    confidence_level = Column(Float)  # 0-1
    confidence_reason = Column(Text)

    # Source data used for estimation
    google_search_volume = Column(Integer)  # Traditional search volume
    social_mentions = Column(Integer)  # Social media mentions

    # Trend
    volume_trend = Column(String(20))  # "growing", "stable", "declining"
    yoy_change = Column(Float)  # Year-over-year change %
    mom_change = Column(Float)  # Month-over-month change %

    # Opportunity scoring
    opportunity_score = Column(Float)  # 0-100, higher = bigger opportunity
    competition_level = Column(String(20))  # "low", "medium", "high"

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        Index('idx_volume_project_month', 'project_id', 'estimate_month'),
        Index('idx_volume_topic', 'topic'),
        UniqueConstraint('project_id', 'keyword_id', 'estimate_month', name='uq_volume_keyword_month'),
    )


# ============================================================================
# OUTREACH OPPORTUNITIES
# ============================================================================

class OutreachOpportunity(Base):
    """Pages that influence AI search - opportunities for outreach"""
    __tablename__ = "outreach_opportunities"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    source_id = Column(UUID(as_uuid=True), ForeignKey("citation_sources.id", ondelete="SET NULL"))

    # The page/source
    page_url = Column(Text, nullable=False)
    page_title = Column(Text)
    page_domain = Column(String(255), nullable=False)

    # Why this is an opportunity
    opportunity_type = Column(String(50), nullable=False)  # "backlink", "mention", "content_update"
    opportunity_reason = Column(Text, nullable=False)

    # Influence metrics
    citation_count = Column(Integer, default=0)  # Times cited by AI
    citation_frequency = Column(Float)  # Citations per 100 queries
    llms_citing = Column(ARRAY(String), default=[])  # Which LLMs cite this

    # Keywords where this source appears
    relevant_keywords = Column(ARRAY(String), default=[])

    # Competitor analysis
    mentions_competitor = Column(Boolean, default=False)
    competitor_mentioned = Column(ARRAY(String), default=[])
    mentions_us = Column(Boolean, default=False)

    # Priority and scoring
    priority_score = Column(Float, nullable=False)  # 0-100
    impact_estimate = Column(String(20))  # "high", "medium", "low"
    effort_estimate = Column(String(20))  # "low", "medium", "high"

    # Contact information (if found)
    contact_email = Column(String(255))
    contact_name = Column(String(255))
    social_profiles = Column(JSONB, default={})

    # Status tracking
    status = Column(Enum(OutreachStatus), default=OutreachStatus.NEW)
    assigned_to = Column(String(255))
    notes = Column(Text)

    # Outreach history
    last_contacted_at = Column(DateTime)
    response_received = Column(Boolean, default=False)
    response_sentiment = Column(Enum(SentimentPolarity))

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        Index('idx_outreach_project', 'project_id', 'priority_score'),
        Index('idx_outreach_status', 'status', 'priority_score'),
        Index('idx_outreach_domain', 'page_domain'),
    )


# ============================================================================
# CONTENT GAPS
# ============================================================================

class ContentGap(Base):
    """Identified content gaps - types of content getting cited that we don't have"""
    __tablename__ = "content_gaps"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)

    # Gap identification
    gap_type = Column(Enum(ContentGapType), nullable=False)
    gap_description = Column(Text, nullable=False)

    # Related keywords
    related_keywords = Column(ARRAY(String), default=[])
    keyword_ids = Column(ARRAY(UUID(as_uuid=True)), default=[])

    # Content type needed
    content_type_needed = Column(String(100))  # "comparison", "guide", "review", "documentation"
    content_format = Column(String(50))  # "article", "video", "infographic", "tool"

    # Evidence - sources being cited instead
    competitor_examples = Column(JSONB, default=[])  # URLs of competitor content
    cited_sources = Column(JSONB, default=[])  # Non-competitor sources

    # Opportunity sizing
    opportunity_score = Column(Float, nullable=False)  # 0-100
    estimated_visibility_gain = Column(Float)  # Potential score improvement

    # Recommended action
    recommended_action = Column(Text, nullable=False)
    action_items = Column(ARRAY(String), default=[])

    # Priority
    priority = Column(String(20))  # "critical", "high", "medium", "low"
    effort_required = Column(String(20))  # "low", "medium", "high"

    # Status
    is_addressed = Column(Boolean, default=False)
    addressed_url = Column(Text)  # URL of content created to fill gap
    addressed_at = Column(DateTime)

    # Metrics after addressing
    visibility_after = Column(Float)
    visibility_improvement = Column(Float)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    __table_args__ = (
        Index('idx_gap_project', 'project_id', 'priority'),
        Index('idx_gap_type', 'gap_type'),
    )


# ============================================================================
# KEYWORD ANALYSIS RESULTS
# ============================================================================

class KeywordAnalysisResult(Base):
    """Detailed analysis results for each keyword run"""
    __tablename__ = "keyword_analysis_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    llm_run_id = Column(UUID(as_uuid=True), ForeignKey("llm_runs.id", ondelete="CASCADE"), nullable=False)
    keyword_id = Column(UUID(as_uuid=True), ForeignKey("keywords.id", ondelete="CASCADE"), nullable=False)
    response_id = Column(UUID(as_uuid=True), ForeignKey("llm_responses.id", ondelete="CASCADE"))

    # LLM details
    provider = Column(Enum(LLMProvider), nullable=False)
    model_name = Column(String(100))

    # Mentions summary
    brand_mentioned = Column(Boolean, default=False)
    brand_position = Column(Integer)  # Position if mentioned (1=first)
    mention_type = Column(Enum(MentionType))
    mention_context = Column(Text)

    # Competitor analysis
    competitors_mentioned = Column(JSONB, default=[])  # [{name, position, context}]
    total_brands_mentioned = Column(Integer, default=0)

    # Citations summary
    total_citations = Column(Integer, default=0)
    our_domain_cited = Column(Boolean, default=False)
    our_domain_citation_position = Column(Integer)
    competitor_domains_cited = Column(ARRAY(String), default=[])

    # Citation details
    citations_summary = Column(JSONB, default=[])  # [{url, domain, position, purpose}]

    # Fan-out queries (if captured)
    fan_out_queries_count = Column(Integer, default=0)
    fan_out_queries = Column(JSONB, default=[])  # List of search queries AI made

    # Shopping recommendations (if applicable)
    has_shopping_recommendations = Column(Boolean, default=False)
    our_product_recommended = Column(Boolean, default=False)
    product_recommendation_position = Column(Integer)

    # Sentiment
    overall_sentiment = Column(Enum(SentimentPolarity))
    brand_sentiment = Column(Enum(SentimentPolarity))
    sentiment_score = Column(Float)  # -1 to 1

    # Visibility scores
    mention_score = Column(Float, default=0)
    position_score = Column(Float, default=0)
    citation_score = Column(Float, default=0)
    sentiment_score_component = Column(Float, default=0)
    total_visibility_score = Column(Float, default=0)

    # Response metadata
    response_length = Column(Integer)
    response_format = Column(String(50))  # "paragraph", "list", "mixed"

    # AIO (AI Overview) tracking
    has_aio = Column(Boolean, default=True)  # Assume true for AI responses (they ARE the AI overview)
    brand_in_aio = Column(Boolean, default=False)  # Whether brand appears in AI overview
    domain_in_aio = Column(Boolean, default=False)  # Whether our domain appears in AI overview

    # Analysis metadata
    analysis_version = Column(String(20))  # Version of analysis algorithm
    analysis_timestamp = Column(DateTime, default=datetime.utcnow)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    keyword = relationship("Keyword", foreign_keys=[keyword_id])

    __table_args__ = (
        Index('idx_analysis_run', 'llm_run_id'),
        Index('idx_analysis_keyword', 'keyword_id'),
        Index('idx_analysis_provider', 'provider', 'created_at'),
    )


# ============================================================================
# GOOGLE AI OVERVIEW (AIO) RESULTS
# ============================================================================

class AIOResult(Base):
    """Google AI Overview analysis results from SERP data"""
    __tablename__ = "aio_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    keyword_id = Column(UUID(as_uuid=True), ForeignKey("keywords.id", ondelete="CASCADE"), nullable=False)
    project_id = Column(UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)

    # Search context
    country = Column(String(10), default="in")  # Country code

    # AIO presence
    has_ai_overview = Column(Boolean, default=False)
    aio_type = Column(String(50))  # "snippet", "answer", "list", "knowledge_graph"
    aio_text = Column(Text)  # The AI Overview text content

    # Brand in AIO
    brand_in_aio = Column(Boolean, default=False)
    brand_aio_position = Column(Integer)  # Position among mentioned brands
    brand_aio_context = Column(Text)  # Context around brand mention

    # Domain in AIO sources
    domain_in_aio = Column(Boolean, default=False)
    domain_aio_position = Column(Integer)  # Position in source list

    # Sources and mentions
    aio_sources = Column(JSONB, default=[])  # List of source URLs
    aio_mentions = Column(JSONB, default=[])  # List of brand/entity mentions

    # Competitor analysis
    competitors_in_aio = Column(JSONB, default=[])  # [{name, position, context}]

    # Organic results analysis
    brand_in_organic = Column(Boolean, default=False)
    brand_organic_position = Column(Integer)  # Position in organic results
    competitors_in_organic = Column(JSONB, default=[])  # [{name, position, url}]
    organic_results = Column(JSONB, default=[])  # Top organic results

    # Knowledge Graph
    has_knowledge_graph = Column(Boolean, default=False)

    # Raw API response for debugging
    raw_response = Column(JSONB)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    keyword = relationship("Keyword", foreign_keys=[keyword_id])

    __table_args__ = (
        Index('idx_aio_keyword', 'keyword_id', 'created_at'),
        Index('idx_aio_project', 'project_id', 'created_at'),
        Index('idx_aio_country', 'country', 'created_at'),
    )


# ============================================================================
# RESPONSE ENTITY EXTRACTION
# ============================================================================

class ExtractedEntity(Base):
    """All entities extracted from AI responses"""
    __tablename__ = "extracted_entities"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    response_id = Column(UUID(as_uuid=True), ForeignKey("llm_responses.id", ondelete="CASCADE"), nullable=False)

    # Entity details
    entity_type = Column(String(50), nullable=False)  # "brand", "product", "person", "url", "price"
    entity_value = Column(Text, nullable=False)
    normalized_value = Column(String(500))  # Normalized/cleaned version

    # Position
    position_in_response = Column(Integer, nullable=False)  # Order of appearance
    character_offset = Column(Integer)

    # Context
    context_snippet = Column(Text)
    sentence = Column(Text)

    # Classification
    is_own_brand = Column(Boolean, default=False)
    is_competitor = Column(Boolean, default=False)

    # Confidence
    extraction_confidence = Column(Float, default=1.0)
    extraction_method = Column(String(50))  # "exact_match", "nlp", "regex"

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index('idx_entity_response', 'response_id'),
        Index('idx_entity_type', 'entity_type', 'normalized_value'),
    )
