"use client";

import { useState } from "react";
import { useProjectStore } from "@/lib/store";
import {
  FileText, Copy, Download, Check, RefreshCw, Globe, Info,
  ChevronDown, ExternalLink, Sparkles, Code, Eye
} from "lucide-react";

export default function LLMsTxtGeneratorPage() {
  const { currentProject } = useProjectStore();
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<"preview" | "code">("preview");

  // Generated LLMs.txt content based on project
  const domain = currentProject?.domain || "example.com";
  const brandName = currentProject?.name || "Your Brand";

  const llmsTxtContent = `# LLMs.txt - AI Crawler Instructions for ${domain}
# Generated by llmscm.com

# Site Information
name: ${brandName}
domain: ${domain}
description: ${brandName} - Leading provider of innovative solutions

# AI Crawling Permissions
User-agent: GPTBot
Allow: /
Allow: /products/
Allow: /services/
Allow: /about/
Allow: /blog/
Disallow: /admin/
Disallow: /private/
Disallow: /api/

User-agent: Google-Extended
Allow: /
Allow: /products/
Allow: /services/
Disallow: /admin/

User-agent: Claude-Web
Allow: /
Allow: /products/
Allow: /services/
Allow: /pricing/
Disallow: /admin/

User-agent: PerplexityBot
Allow: /
Disallow: /admin/

User-agent: Amazonbot
Allow: /
Disallow: /admin/

# Preferred Citation Format
citation-format: "${brandName} (${domain})"
citation-url: https://${domain}

# Brand Information for AI
brand-name: ${brandName}
brand-aliases: ${brandName.toLowerCase()}, ${brandName.replace(/\s+/g, "")}
primary-contact: info@${domain}

# Content Categories
categories:
  - products
  - services
  - solutions
  - pricing
  - documentation
  - blog

# Key Pages for AI Understanding
important-pages:
  - https://${domain}/
  - https://${domain}/products
  - https://${domain}/pricing
  - https://${domain}/about
  - https://${domain}/contact

# Structured Data Available
structured-data: true
schema-types:
  - Organization
  - Product
  - FAQPage
  - Article

# Update Frequency
sitemap: https://${domain}/sitemap.xml
update-frequency: weekly

# Contact for AI-related queries
ai-contact: ai@${domain}
`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(llmsTxtContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([llmsTxtContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "llms.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => setGenerating(false), 1500);
  };

  return (
    <div className="space-y-6 max-w-5xl">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-violet-500 to-indigo-600 flex items-center justify-center shadow-lg">
              <FileText className="h-6 w-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">LLMs.txt Generator</h1>
              <p className="text-gray-500">Create an AI-optimized llms.txt file for your website</p>
            </div>
          </div>
        </div>
      </div>

      {/* Info Banner */}
      <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex gap-3">
        <Info className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
        <div>
          <p className="text-blue-900 font-medium">What is llms.txt?</p>
          <p className="text-blue-700 text-sm mt-1">
            Similar to robots.txt, llms.txt is a proposed standard that tells AI crawlers how to interact with your website.
            It helps AI models understand your brand, find important content, and cite you correctly in responses.
          </p>
          <a href="#" className="text-blue-600 text-sm font-medium inline-flex items-center gap-1 mt-2 hover:underline">
            Learn more about llms.txt <ExternalLink className="w-3 h-3" />
          </a>
        </div>
      </div>

      {/* Generator Card */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        {/* Tabs */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <div className="flex gap-4">
            <button
              onClick={() => setActiveTab("preview")}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                activeTab === "preview"
                  ? "bg-violet-100 text-violet-700"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              <Eye className="w-4 h-4" />
              Preview
            </button>
            <button
              onClick={() => setActiveTab("code")}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
                activeTab === "code"
                  ? "bg-violet-100 text-violet-700"
                  : "text-gray-600 hover:bg-gray-100"
              }`}
            >
              <Code className="w-4 h-4" />
              Raw Code
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              {generating ? (
                <RefreshCw className="w-4 h-4 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4" />
              )}
              Regenerate
            </button>
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-3 py-1.5 border border-gray-200 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-green-500" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy
                </>
              )}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-1.5 bg-violet-600 text-white rounded-lg text-sm font-medium hover:bg-violet-700 transition-colors"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-6">
          {activeTab === "preview" ? (
            <div className="space-y-4">
              {/* Site Info */}
              <div className="p-4 bg-gray-50 rounded-lg">
                <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Globe className="w-4 h-4" />
                  Site Information
                </h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">Name:</span>
                    <span className="ml-2 text-gray-900 font-medium">{brandName}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">Domain:</span>
                    <span className="ml-2 text-gray-900 font-medium">{domain}</span>
                  </div>
                </div>
              </div>

              {/* AI Crawler Rules */}
              <div className="p-4 bg-gray-50 rounded-lg">
                <h3 className="font-semibold text-gray-900 mb-3">AI Crawler Permissions</h3>
                <div className="space-y-3">
                  {[
                    { name: "GPTBot (OpenAI)", status: "allowed", pages: "All public pages" },
                    { name: "Google-Extended", status: "allowed", pages: "Products & Services" },
                    { name: "Claude-Web", status: "allowed", pages: "All public pages" },
                    { name: "PerplexityBot", status: "allowed", pages: "All public pages" },
                  ].map((crawler) => (
                    <div key={crawler.name} className="flex items-center justify-between py-2 border-b border-gray-200 last:border-0">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-green-100 flex items-center justify-center">
                          <Check className="w-4 h-4 text-green-600" />
                        </div>
                        <div>
                          <p className="font-medium text-gray-900 text-sm">{crawler.name}</p>
                          <p className="text-xs text-gray-500">{crawler.pages}</p>
                        </div>
                      </div>
                      <span className="text-xs px-2 py-1 bg-green-100 text-green-700 rounded-full">
                        {crawler.status}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Citation Format */}
              <div className="p-4 bg-gray-50 rounded-lg">
                <h3 className="font-semibold text-gray-900 mb-3">Preferred Citation</h3>
                <code className="block p-3 bg-white rounded border text-sm text-gray-800">
                  {brandName} ({domain})
                </code>
              </div>
            </div>
          ) : (
            <div className="relative">
              <pre className="p-4 bg-gray-900 text-gray-100 rounded-lg overflow-x-auto text-sm font-mono leading-relaxed max-h-[500px] overflow-y-auto">
                {llmsTxtContent}
              </pre>
            </div>
          )}
        </div>
      </div>

      {/* Installation Guide */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="text-lg font-bold text-gray-900 mb-4">How to Install</h2>
        <div className="space-y-4">
          <div className="flex gap-4">
            <div className="w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center font-bold text-sm shrink-0">
              1
            </div>
            <div>
              <p className="font-medium text-gray-900">Download the llms.txt file</p>
              <p className="text-sm text-gray-500 mt-1">
                Click the download button above to get your customized llms.txt file.
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center font-bold text-sm shrink-0">
              2
            </div>
            <div>
              <p className="font-medium text-gray-900">Upload to your website root</p>
              <p className="text-sm text-gray-500 mt-1">
                Place the file at <code className="px-1.5 py-0.5 bg-gray-100 rounded text-xs">https://{domain}/llms.txt</code>
              </p>
            </div>
          </div>
          <div className="flex gap-4">
            <div className="w-8 h-8 rounded-full bg-violet-100 text-violet-600 flex items-center justify-center font-bold text-sm shrink-0">
              3
            </div>
            <div>
              <p className="font-medium text-gray-900">Verify installation</p>
              <p className="text-sm text-gray-500 mt-1">
                Visit your llms.txt URL to confirm it's accessible, then use our AI Crawlability Checker to validate.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
